### PR TITLE
Volume differences

### PR DESCRIPTION
**Pull request by kiates**
This is in regard to issue #80 

I think OpenAL is used for all three platforms (Win, Linux, OSX), so I would expect the behavior to be consistent, and therefore my change working the same on all three.  I'm not 100% sure though.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
This one definitely seemed odd, and sure enough, my ears got definitely blasted by a couple XACT games I had to test. This _might_ be Win32-specific; try the stock OpenAL Soft binary first...

http://kcat.strangesoft.net/openal-binaries/openal-soft-1.17.2-bin.zip

... and if that's still too soft, you may want to look into the Win32 backends:

https://github.com/kcat/openal-soft/tree/master/Alc/backends

If you want some more XACT games to test against, I have these games on Steam with 'fna-unstable' branches for Windows (sometimes the branch is named 'fna-win32'):

- Rogue Legacy
- Dust: An Elysian Tail
- Salt and Sanctuary

**Comment by kiates** [comment]
I hadn't tried this fix in Solaroids yet, so I did a little XNA/FNA comparison on the same Win32 box.  It seems that the audio that doesn't use RPC presets (from what I can tell) plays louder with the fix (non-positional audio effects, and background music), but those that do use them play at the same level.  If this is the case it suggests the correction may be somewhere else other than at the OpenAL interface.

My testbench was focused on RPC aspects and didn't have any "simple" sounds.  I'll look into it more and update this pull request.

**Comment by flibitijibibo** [comment]
The way I usually debug volunes is by going to the sfi.Volume set at the end of INTERNAL_update and just printf spam all the volume attribs that get multiplied into the final volume. Crude, but it tells you everything you need without a lot of stepping!

**Comment by flibitijibibo** [comment]
Since the current patchset doesn't fix the accuracy issue and it has those other commits from previous PRs I'll go ahead and close this one, but we still have #80 open to dig into this further.

**Pull request closed without merging**
