### PR TITLE
Mass Refactoring.

### PR DESCRIPTION
**Pull request by Hawkeye4040**
Mass refactoring and code cleanup.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Hilarious.

**Comment by Hawkeye4040** [comment]
What do you mean?

**Comment by flibitijibibo** [comment]
Wait... was this actually a real patch? I thought it was just a fork that accidentally opened to the wrong remote.

**Comment by Hawkeye4040** [comment]
Yeah it's a real patch.

**Comment by Hawkeye4040** [comment]
Take a look I cleaned up a lot.

**Comment by Hawkeye4040** [comment]
Oh I see what you mean I just forked it for now because I was thinking about making some other changes that after looking into it I may not have to make now. Still thinking on that one. But anyway this is a good one to merge to master here.

**Comment by flibitijibibo** [comment]
A single commit that _grossly_ violates style, obliterates spacing, and breaks compatibility with our compiler with no functional change, a patch does not make. This is functionally worthless. Please do not send patches like this to anyone for any software, it's a waste of reviewers' time.

**Comment by Hawkeye4040** [comment]
Okay I guess I won't be helping you anymore since you're all butt hurt that someone cleaned up your sloppy code. Fork it is. You realize you don't own XNA right? It's also not a waste of time. You also contradict yourself quite a bit there. If there was no functional change then how would it break compatibility with the compiler? Violates style? I intentionally didn't use that pass since I could tell our formatting styles were different.

Without being able to hear the stress in your voice I would dare say you're butt hurt.

**Comment by flibitijibibo** [comment]
I can't say I was thrilled with the diff, but the replies were absolutely worth it. Thank you for your time, please do not delete these posts!

**Pull request closed without merging**
